---
- name: Configure firewalld package
  package:
    name: firewalld
    state: "{{ firewalld_package_state }}"

- name: Configure firewalld service
  service:
    name: "{{ firewalld_service_name }}"
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"

- name: Configure firewalld default zone
  firewalld:
    interface: "{{ firewalld_default_interface }}"
    zone: "{{ firewalld_default_zone }}"
    state: enabled
    permanent: yes
